### ISSUE TITLE
Error on blender 5.1

### ISSUE THREAD

**Issue by Felzow47** [AIGODLIKE/Blender-CWF-Remesher#3]
Python: Traceback (most recent call last):
  File "C:\Users\Felzow47\AppData\Roaming\Blender Foundation\Blender\5.1\scripts\addons\Blender-CWF-Remesher\src\cwf\operators.py", line 43, in invoke
    return self.execute(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Felzow47\AppData\Roaming\Blender Foundation\Blender\5.1\scripts\addons\Blender-CWF-Remesher\src\cwf\operators.py", line 92, in execute
    from ...cxxlibs import remesh
  File "C:\Users\Felzow47\AppData\Roaming\Blender Foundation\Blender\5.1\scripts\addons\Blender-CWF-Remesher\cxxlibs\__init__.py", line 5, in <module>
    from .windows import remesh
ImportError: cannot import name 'remesh' from 'Blender-CWF-Remesher.cxxlibs.windows' (unknown location)

**Comment by cgdive** [comment]
Looks like it only works with 3.6.
